/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package leaderboard

import spock.lang.Ignore
import spock.lang.Specification

class LibraryTest extends Specification {

    @Ignore
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new App()

        when:
        lib.handleRequest(null, null);

        then:
        result == 0
    }
}
